language: d
sudo: false
install:
  - gem install bundler
  - bundle install
  - git clone https://github.com/martine/ninja.git
  - cd ninja
  - ./configure.py --bootstrap
  - export PATH=$PWD:$PATH
  - cd ..
  - dub fetch unit-threaded --version=0.5.5
  - dub fetch cerealed --version=0.6.3
  - git clone https://github.com/D-Programming-Language/dub.git
  - cd dub
  - dub build
  - export PATH=$PWD/bin:$PATH
  - cd ..
  - git clone https://github.com/atilaneves/reggae-python
  - cd reggae-python
  - export PYTHONPATH=$PWD
  - cd ..
  - git clone https://github.com/atilaneves/reggae-ruby
  - cd reggae-ruby
  - export RUBYLIB=$PWD/lib
  - export PATH=$PATH:$PWD/bin
  - cd ..
  - npm install reggae-js
  - export PATH=$PATH:$PWD/node_modules/reggae-js/bin
  - export NODE_PATH=$PWD/node_modules/reggae-js/lib

script:
  - ./bootstrap.sh make
  - bin/ut
  - cucumber --tags ~@tup --tags ~@ruby --tags ~@lua
